import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { ArrowLeft, Download, MapPin, Printer, FileText } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { Badge } from "@/components/ui/badge";
import { TripSubNav } from "@/components/trip-sub-nav";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/lib/use-auth";
import { format } from "date-fns";

export const Route = createFileRoute("/_app/trips/$tripId/invoice")({
  head: () => ({ meta: [{ title: "Invoice — Traveloop" }] }),
  component: Invoice,
});

function Invoice() {
  const { tripId } = Route.useParams();
  const { user } = useAuth();

  const { data: trip } = useQuery({
    queryKey: ["trip", tripId],
    queryFn: async () => {
      const { data, error } = await supabase.from("trips").select("*").eq("id", tripId).single();
      if (error) throw error;
      return data;
    },
  });

  const { data: profile } = useQuery({
    queryKey: ["profile", user?.id],
    enabled: !!user,
    queryFn: async () => {
      const { data } = await supabase.from("profiles").select("*").eq("id", user!.id).single();
      return data;
    },
  });

  const { data: sections, isLoading } = useQuery({
    queryKey: ["itinerary", tripId],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("trip_sections").select("*, activities(*)").eq("trip_id", tripId).order("position");
      if (error) throw error;
      return data as Array<{
        id: string; name: string; city: string | null; budget: number | null;
        activities: Array<{ id: string; title: string; category: string | null; cost: number | null; duration_hours: number | null }>;
      }>;
    },
  });

  const allActivities = (sections ?? []).flatMap((s) =>
    s.activities.map((a) => ({ ...a, sectionName: s.name }))
  );
  const subtotal = allActivities.reduce((sum, a) => sum + Number(a.cost ?? 0), 0);
  const tax = subtotal * 0; // No tax by default
  const grandTotal = subtotal + tax;
  const invoiceNumber = `TL-${tripId.slice(0, 8).toUpperCase()}`;
  const invoiceDate = format(new Date(), "MMM d, yyyy");

  const handleDownloadPDF = async () => {
    const { default: jsPDF } = await import("jspdf");
    const { default: autoTable } = await import("jspdf-autotable");

    const doc = new jsPDF();

    // Header
    doc.setFontSize(22);
    doc.setFont("helvetica", "bold");
    doc.text("Traveloop", 14, 22);
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100);
    doc.text("Travel Invoice", 14, 28);

    // Invoice Info
    doc.setFontSize(10);
    doc.setTextColor(50);
    doc.text(`Invoice #: ${invoiceNumber}`, 140, 16);
    doc.text(`Date: ${invoiceDate}`, 140, 22);
    doc.text(`Trip: ${trip?.title ?? ""}`, 140, 28);

    // Billed To
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(30);
    doc.text("Billed To:", 14, 42);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text(profile?.full_name ?? "Traveler", 14, 48);
    doc.text(profile?.email ?? "", 14, 53);
    if (trip?.destination) doc.text(`Destination: ${trip.destination}`, 14, 58);
    if (trip?.start_date && trip?.end_date) {
      doc.text(`Dates: ${format(new Date(trip.start_date), "MMM d")} — ${format(new Date(trip.end_date), "MMM d, yyyy")}`, 14, 63);
    }

    // Table
    const rows = allActivities.map((a, i) => [
      String(i + 1),
      a.title,
      a.sectionName,
      a.category ?? "—",
      a.duration_hours ? `${a.duration_hours}h` : "—",
      `$${Number(a.cost ?? 0).toFixed(2)}`,
    ]);

    autoTable(doc, {
      startY: 72,
      head: [["#", "Activity", "Section", "Category", "Duration", "Cost"]],
      body: rows,
      theme: "striped",
      headStyles: { fillColor: [13, 148, 136], textColor: 255, fontStyle: "bold" },
      styles: { fontSize: 9, cellPadding: 3 },
      columnStyles: { 0: { cellWidth: 10 }, 5: { halign: "right" } },
    });

    // Totals
    const finalY = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 8;
    doc.setFontSize(10);
    doc.text(`Subtotal:`, 140, finalY);
    doc.text(`$${subtotal.toFixed(2)}`, 185, finalY, { align: "right" });
    doc.text(`Tax (0%):`, 140, finalY + 6);
    doc.text(`$${tax.toFixed(2)}`, 185, finalY + 6, { align: "right" });
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text(`Grand Total:`, 140, finalY + 14);
    doc.text(`$${grandTotal.toFixed(2)}`, 185, finalY + 14, { align: "right" });

    // Footer
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(150);
    doc.text("Generated by Traveloop — multi-city travel planning", 14, 285);

    doc.save(`traveloop-invoice-${invoiceNumber}.pdf`);
  };

  return (
    <div className="space-y-6">
      <div>
        <Button asChild variant="ghost" size="sm" className="mb-2 -ml-2">
          <Link to="/trips"><ArrowLeft className="mr-1 h-4 w-4" /> All trips</Link>
        </Button>
        <h1 className="font-display text-3xl font-bold">Invoice</h1>
        {trip?.destination && (
          <div className="mt-1 flex items-center gap-1 text-sm text-muted-foreground"><MapPin className="h-3.5 w-3.5" /> {trip.destination}</div>
        )}
      </div>

      <TripSubNav tripId={tripId} />

      {isLoading ? (
        <Skeleton className="h-96 rounded-2xl" />
      ) : (
        <>
          {/* Invoice Header */}
          <div className="rounded-2xl border border-border bg-card shadow-soft overflow-hidden">
            <div className="bg-gradient-hero p-6 text-primary-foreground">
              <div className="flex flex-wrap items-start justify-between gap-4">
                <div>
                  <div className="flex items-center gap-2 mb-1">
                    <FileText className="h-5 w-5" />
                    <span className="font-display text-lg font-bold">Traveloop</span>
                  </div>
                  <p className="text-sm text-white/80">Travel Invoice</p>
                </div>
                <div className="text-right text-sm">
                  <div className="font-medium">Invoice #{invoiceNumber}</div>
                  <div className="text-white/80">Date: {invoiceDate}</div>
                </div>
              </div>
            </div>

            {/* Billed To */}
            <div className="border-b border-border p-5">
              <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
                <div>
                  <div className="text-xs text-muted-foreground mb-1">Billed To</div>
                  <div className="font-medium">{profile?.full_name ?? "Traveler"}</div>
                  <div className="text-sm text-muted-foreground">{profile?.email ?? ""}</div>
                </div>
                <div>
                  <div className="text-xs text-muted-foreground mb-1">Trip Details</div>
                  <div className="font-medium">{trip?.title}</div>
                  {trip?.start_date && trip?.end_date && (
                    <div className="text-sm text-muted-foreground">
                      {format(new Date(trip.start_date), "MMM d")} — {format(new Date(trip.end_date), "MMM d, yyyy")}
                    </div>
                  )}
                </div>
              </div>
            </div>

            {/* Line Items Table */}
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr className="border-b border-border bg-muted/50">
                    <th className="px-4 py-3 text-left text-xs font-medium text-muted-foreground w-10">#</th>
                    <th className="px-4 py-3 text-left text-xs font-medium text-muted-foreground">Activity</th>
                    <th className="px-4 py-3 text-left text-xs font-medium text-muted-foreground">Section</th>
                    <th className="px-4 py-3 text-left text-xs font-medium text-muted-foreground">Category</th>
                    <th className="px-4 py-3 text-right text-xs font-medium text-muted-foreground">Duration</th>
                    <th className="px-4 py-3 text-right text-xs font-medium text-muted-foreground">Cost</th>
                  </tr>
                </thead>
                <tbody>
                  {allActivities.length === 0 ? (
                    <tr><td colSpan={6} className="px-4 py-8 text-center text-muted-foreground">No activities to invoice.</td></tr>
                  ) : (
                    allActivities.map((a, i) => (
                      <tr key={a.id} className="border-b border-border last:border-0 hover:bg-muted/30 transition-base">
                        <td className="px-4 py-3 text-muted-foreground">{i + 1}</td>
                        <td className="px-4 py-3 font-medium">{a.title}</td>
                        <td className="px-4 py-3 text-muted-foreground">{a.sectionName}</td>
                        <td className="px-4 py-3">
                          {a.category ? <Badge variant="secondary" className="text-[10px]">{a.category}</Badge> : "—"}
                        </td>
                        <td className="px-4 py-3 text-right text-muted-foreground">
                          {a.duration_hours ? `${a.duration_hours}h` : "—"}
                        </td>
                        <td className="px-4 py-3 text-right font-medium">${Number(a.cost ?? 0).toFixed(2)}</td>
                      </tr>
                    ))
                  )}
                </tbody>
              </table>
            </div>

            {/* Totals */}
            <div className="border-t border-border bg-muted/20 p-5">
              <div className="ml-auto max-w-xs space-y-2">
                <div className="flex justify-between text-sm">
                  <span className="text-muted-foreground">Subtotal</span>
                  <span>${subtotal.toFixed(2)}</span>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-muted-foreground">Tax (0%)</span>
                  <span>${tax.toFixed(2)}</span>
                </div>
                <div className="flex justify-between border-t border-border pt-2 text-base font-bold">
                  <span>Grand Total</span>
                  <span className="text-primary">${grandTotal.toFixed(2)}</span>
                </div>
              </div>
            </div>
          </div>

          {/* Action Buttons */}
          <div className="flex flex-wrap gap-2">
            <Button onClick={handleDownloadPDF} className="shadow-soft">
              <Download className="mr-1 h-4 w-4" /> Download PDF
            </Button>
            <Button variant="outline" onClick={() => window.print()}>
              <Printer className="mr-1 h-4 w-4" /> Print
            </Button>
          </div>
        </>
      )}
    </div>
  );
}
