/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTripsRouteImport } from './routes/_app.trips'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppExploreRouteImport } from './routes/_app.explore'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCommunityRouteImport } from './routes/_app.community'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AppTripsNewRouteImport } from './routes/_app.trips.new'
import { Route as AppTripsTripIdSettingsRouteImport } from './routes/_app.trips.$tripId.settings'
import { Route as AppTripsTripIdPackingRouteImport } from './routes/_app.trips.$tripId.packing'
import { Route as AppTripsTripIdOverviewRouteImport } from './routes/_app.trips.$tripId.overview'
import { Route as AppTripsTripIdNotesRouteImport } from './routes/_app.trips.$tripId.notes'
import { Route as AppTripsTripIdItineraryRouteImport } from './routes/_app.trips.$tripId.itinerary'
import { Route as AppTripsTripIdInvoiceRouteImport } from './routes/_app.trips.$tripId.invoice'
import { Route as AppTripsTripIdBuilderRouteImport } from './routes/_app.trips.$tripId.builder'
import { Route as AppTripsTripIdBudgetRouteImport } from './routes/_app.trips.$tripId.budget'
import { Route as AppTripsTripIdBookingsRouteImport } from './routes/_app.trips.$tripId.bookings'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTripsRoute = AppTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppExploreRoute = AppExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunityRoute = AppCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppTripsNewRoute = AppTripsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppTripsRoute,
} as any)
const AppTripsTripIdSettingsRoute = AppTripsTripIdSettingsRouteImport.update({
  id: '/$tripId/settings',
  path: '/$tripId/settings',
  getParentRoute: () => AppTripsRoute,
} as any)
const AppTripsTripIdPackingRoute = AppTripsTripIdPackingRouteImport.update({
  id: '/$tripId/packing',
  path: '/$tripId/packing',
  getParentRoute: () => AppTripsRoute,
} as any)
const AppTripsTripIdOverviewRoute = AppTripsTripIdOverviewRouteImport.update({
  id: '/$tripId/overview',
  path: '/$tripId/overview',
  getParentRoute: () => AppTripsRoute,
} as any)
const AppTripsTripIdNotesRoute = AppTripsTripIdNotesRouteImport.update({
  id: '/$tripId/notes',
  path: '/$tripId/notes',
  getParentRoute: () => AppTripsRoute,
} as any)
const AppTripsTripIdItineraryRoute = AppTripsTripIdItineraryRouteImport.update({
  id: '/$tripId/itinerary',
  path: '/$tripId/itinerary',
  getParentRoute: () => AppTripsRoute,
} as any)
const AppTripsTripIdInvoiceRoute = AppTripsTripIdInvoiceRouteImport.update({
  id: '/$tripId/invoice',
  path: '/$tripId/invoice',
  getParentRoute: () => AppTripsRoute,
} as any)
const AppTripsTripIdBuilderRoute = AppTripsTripIdBuilderRouteImport.update({
  id: '/$tripId/builder',
  path: '/$tripId/builder',
  getParentRoute: () => AppTripsRoute,
} as any)
const AppTripsTripIdBudgetRoute = AppTripsTripIdBudgetRouteImport.update({
  id: '/$tripId/budget',
  path: '/$tripId/budget',
  getParentRoute: () => AppTripsRoute,
} as any)
const AppTripsTripIdBookingsRoute = AppTripsTripIdBookingsRouteImport.update({
  id: '/$tripId/bookings',
  path: '/$tripId/bookings',
  getParentRoute: () => AppTripsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/analytics': typeof AppAnalyticsRoute
  '/community': typeof AppCommunityRoute
  '/dashboard': typeof AppDashboardRoute
  '/explore': typeof AppExploreRoute
  '/profile': typeof AppProfileRoute
  '/trips': typeof AppTripsRouteWithChildren
  '/trips/new': typeof AppTripsNewRoute
  '/trips/$tripId/bookings': typeof AppTripsTripIdBookingsRoute
  '/trips/$tripId/budget': typeof AppTripsTripIdBudgetRoute
  '/trips/$tripId/builder': typeof AppTripsTripIdBuilderRoute
  '/trips/$tripId/invoice': typeof AppTripsTripIdInvoiceRoute
  '/trips/$tripId/itinerary': typeof AppTripsTripIdItineraryRoute
  '/trips/$tripId/notes': typeof AppTripsTripIdNotesRoute
  '/trips/$tripId/overview': typeof AppTripsTripIdOverviewRoute
  '/trips/$tripId/packing': typeof AppTripsTripIdPackingRoute
  '/trips/$tripId/settings': typeof AppTripsTripIdSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/analytics': typeof AppAnalyticsRoute
  '/community': typeof AppCommunityRoute
  '/dashboard': typeof AppDashboardRoute
  '/explore': typeof AppExploreRoute
  '/profile': typeof AppProfileRoute
  '/trips': typeof AppTripsRouteWithChildren
  '/trips/new': typeof AppTripsNewRoute
  '/trips/$tripId/bookings': typeof AppTripsTripIdBookingsRoute
  '/trips/$tripId/budget': typeof AppTripsTripIdBudgetRoute
  '/trips/$tripId/builder': typeof AppTripsTripIdBuilderRoute
  '/trips/$tripId/invoice': typeof AppTripsTripIdInvoiceRoute
  '/trips/$tripId/itinerary': typeof AppTripsTripIdItineraryRoute
  '/trips/$tripId/notes': typeof AppTripsTripIdNotesRoute
  '/trips/$tripId/overview': typeof AppTripsTripIdOverviewRoute
  '/trips/$tripId/packing': typeof AppTripsTripIdPackingRoute
  '/trips/$tripId/settings': typeof AppTripsTripIdSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/community': typeof AppCommunityRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/explore': typeof AppExploreRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/trips': typeof AppTripsRouteWithChildren
  '/_app/trips/new': typeof AppTripsNewRoute
  '/_app/trips/$tripId/bookings': typeof AppTripsTripIdBookingsRoute
  '/_app/trips/$tripId/budget': typeof AppTripsTripIdBudgetRoute
  '/_app/trips/$tripId/builder': typeof AppTripsTripIdBuilderRoute
  '/_app/trips/$tripId/invoice': typeof AppTripsTripIdInvoiceRoute
  '/_app/trips/$tripId/itinerary': typeof AppTripsTripIdItineraryRoute
  '/_app/trips/$tripId/notes': typeof AppTripsTripIdNotesRoute
  '/_app/trips/$tripId/overview': typeof AppTripsTripIdOverviewRoute
  '/_app/trips/$tripId/packing': typeof AppTripsTripIdPackingRoute
  '/_app/trips/$tripId/settings': typeof AppTripsTripIdSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/analytics'
    | '/community'
    | '/dashboard'
    | '/explore'
    | '/profile'
    | '/trips'
    | '/trips/new'
    | '/trips/$tripId/bookings'
    | '/trips/$tripId/budget'
    | '/trips/$tripId/builder'
    | '/trips/$tripId/invoice'
    | '/trips/$tripId/itinerary'
    | '/trips/$tripId/notes'
    | '/trips/$tripId/overview'
    | '/trips/$tripId/packing'
    | '/trips/$tripId/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/analytics'
    | '/community'
    | '/dashboard'
    | '/explore'
    | '/profile'
    | '/trips'
    | '/trips/new'
    | '/trips/$tripId/bookings'
    | '/trips/$tripId/budget'
    | '/trips/$tripId/builder'
    | '/trips/$tripId/invoice'
    | '/trips/$tripId/itinerary'
    | '/trips/$tripId/notes'
    | '/trips/$tripId/overview'
    | '/trips/$tripId/packing'
    | '/trips/$tripId/settings'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/analytics'
    | '/_app/community'
    | '/_app/dashboard'
    | '/_app/explore'
    | '/_app/profile'
    | '/_app/trips'
    | '/_app/trips/new'
    | '/_app/trips/$tripId/bookings'
    | '/_app/trips/$tripId/budget'
    | '/_app/trips/$tripId/builder'
    | '/_app/trips/$tripId/invoice'
    | '/_app/trips/$tripId/itinerary'
    | '/_app/trips/$tripId/notes'
    | '/_app/trips/$tripId/overview'
    | '/_app/trips/$tripId/packing'
    | '/_app/trips/$tripId/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/trips': {
      id: '/_app/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof AppTripsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/explore': {
      id: '/_app/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AppExploreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/community': {
      id: '/_app/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AppCommunityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trips/new': {
      id: '/_app/trips/new'
      path: '/new'
      fullPath: '/trips/new'
      preLoaderRoute: typeof AppTripsNewRouteImport
      parentRoute: typeof AppTripsRoute
    }
    '/_app/trips/$tripId/settings': {
      id: '/_app/trips/$tripId/settings'
      path: '/$tripId/settings'
      fullPath: '/trips/$tripId/settings'
      preLoaderRoute: typeof AppTripsTripIdSettingsRouteImport
      parentRoute: typeof AppTripsRoute
    }
    '/_app/trips/$tripId/packing': {
      id: '/_app/trips/$tripId/packing'
      path: '/$tripId/packing'
      fullPath: '/trips/$tripId/packing'
      preLoaderRoute: typeof AppTripsTripIdPackingRouteImport
      parentRoute: typeof AppTripsRoute
    }
    '/_app/trips/$tripId/overview': {
      id: '/_app/trips/$tripId/overview'
      path: '/$tripId/overview'
      fullPath: '/trips/$tripId/overview'
      preLoaderRoute: typeof AppTripsTripIdOverviewRouteImport
      parentRoute: typeof AppTripsRoute
    }
    '/_app/trips/$tripId/notes': {
      id: '/_app/trips/$tripId/notes'
      path: '/$tripId/notes'
      fullPath: '/trips/$tripId/notes'
      preLoaderRoute: typeof AppTripsTripIdNotesRouteImport
      parentRoute: typeof AppTripsRoute
    }
    '/_app/trips/$tripId/itinerary': {
      id: '/_app/trips/$tripId/itinerary'
      path: '/$tripId/itinerary'
      fullPath: '/trips/$tripId/itinerary'
      preLoaderRoute: typeof AppTripsTripIdItineraryRouteImport
      parentRoute: typeof AppTripsRoute
    }
    '/_app/trips/$tripId/invoice': {
      id: '/_app/trips/$tripId/invoice'
      path: '/$tripId/invoice'
      fullPath: '/trips/$tripId/invoice'
      preLoaderRoute: typeof AppTripsTripIdInvoiceRouteImport
      parentRoute: typeof AppTripsRoute
    }
    '/_app/trips/$tripId/builder': {
      id: '/_app/trips/$tripId/builder'
      path: '/$tripId/builder'
      fullPath: '/trips/$tripId/builder'
      preLoaderRoute: typeof AppTripsTripIdBuilderRouteImport
      parentRoute: typeof AppTripsRoute
    }
    '/_app/trips/$tripId/budget': {
      id: '/_app/trips/$tripId/budget'
      path: '/$tripId/budget'
      fullPath: '/trips/$tripId/budget'
      preLoaderRoute: typeof AppTripsTripIdBudgetRouteImport
      parentRoute: typeof AppTripsRoute
    }
    '/_app/trips/$tripId/bookings': {
      id: '/_app/trips/$tripId/bookings'
      path: '/$tripId/bookings'
      fullPath: '/trips/$tripId/bookings'
      preLoaderRoute: typeof AppTripsTripIdBookingsRouteImport
      parentRoute: typeof AppTripsRoute
    }
  }
}

interface AppTripsRouteChildren {
  AppTripsNewRoute: typeof AppTripsNewRoute
  AppTripsTripIdBookingsRoute: typeof AppTripsTripIdBookingsRoute
  AppTripsTripIdBudgetRoute: typeof AppTripsTripIdBudgetRoute
  AppTripsTripIdBuilderRoute: typeof AppTripsTripIdBuilderRoute
  AppTripsTripIdInvoiceRoute: typeof AppTripsTripIdInvoiceRoute
  AppTripsTripIdItineraryRoute: typeof AppTripsTripIdItineraryRoute
  AppTripsTripIdNotesRoute: typeof AppTripsTripIdNotesRoute
  AppTripsTripIdOverviewRoute: typeof AppTripsTripIdOverviewRoute
  AppTripsTripIdPackingRoute: typeof AppTripsTripIdPackingRoute
  AppTripsTripIdSettingsRoute: typeof AppTripsTripIdSettingsRoute
}

const AppTripsRouteChildren: AppTripsRouteChildren = {
  AppTripsNewRoute: AppTripsNewRoute,
  AppTripsTripIdBookingsRoute: AppTripsTripIdBookingsRoute,
  AppTripsTripIdBudgetRoute: AppTripsTripIdBudgetRoute,
  AppTripsTripIdBuilderRoute: AppTripsTripIdBuilderRoute,
  AppTripsTripIdInvoiceRoute: AppTripsTripIdInvoiceRoute,
  AppTripsTripIdItineraryRoute: AppTripsTripIdItineraryRoute,
  AppTripsTripIdNotesRoute: AppTripsTripIdNotesRoute,
  AppTripsTripIdOverviewRoute: AppTripsTripIdOverviewRoute,
  AppTripsTripIdPackingRoute: AppTripsTripIdPackingRoute,
  AppTripsTripIdSettingsRoute: AppTripsTripIdSettingsRoute,
}

const AppTripsRouteWithChildren = AppTripsRoute._addFileChildren(
  AppTripsRouteChildren,
)

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppCommunityRoute: typeof AppCommunityRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppExploreRoute: typeof AppExploreRoute
  AppProfileRoute: typeof AppProfileRoute
  AppTripsRoute: typeof AppTripsRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppCommunityRoute: AppCommunityRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppExploreRoute: AppExploreRoute,
  AppProfileRoute: AppProfileRoute,
  AppTripsRoute: AppTripsRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
